Refactor CI workflows and Docker configurations for improved structure and dependency management

diff --git a/.github/workflows/ci_on_ubuntu.yml b/.github/workflows/ci_on_ubuntu.yml
--- a/.github/workflows/ci_on_ubuntu.yml
+++ b/.github/workflows/ci_on_ubuntu.yml
@@ -13,9 +13,6 @@ on:
 jobs:
   process_labels:
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      pull-requests: read
     outputs:
       is_docker: ${{ steps.step1.outputs.is_docker }}
     steps:
@@ -31,34 +28,65 @@ jobs:
             echo "is_docker=false" >> "$GITHUB_OUTPUT"
           fi
 
-  test_python_espnet2:
+  setup_environment:
     runs-on: ubuntu-latest
     needs: process_labels
-    permissions:
-      contents: read
-      packages: read
     if: |
       github.event.pull_request.draft == false
-    container:
-      image: ghcr.io/${{ github.repository_owner }}/espnet-ci:py${{ matrix.python-version }}-torch${{ matrix.pytorch-version }}
-      credentials:
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
     strategy:
       max-parallel: 20
       matrix:
         python-version: ["3.10", "3.12"]
         pytorch-version: [2.5.1, 2.7.1, 2.8.0, 2.9.1]
+        chainer-version: [6.0.0]
+        use-conda: [false]
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@master
       - uses: actions/cache@v5
         with:
           path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}
+          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      # - name: Cache tools
+      #   uses: actions/cache@v5
+      #   with:
+      #     path: tools
+      #     key: ${{ runner.os }}-tools-${{ github.run_id }}-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      - name: Make environment
+        uses: ./.github/actions/prepare-environment
+        with:
+          os-version: ubuntu
+          python-version: ${{ matrix.python-version }}
+          pytorch-version: ${{ matrix.pytorch-version }}
+          chainer-version: ${{ matrix.chainer-version }}
+          use-conda: ${{ matrix.use-conda }}
+      - name: Install Kaldi
+        run: ./ci/install_kaldi.sh
+
+  test_python_espnet2:
+    runs-on: ubuntu-latest
+    needs: setup_environment
+    if: |
+      github.event.pull_request.draft == false
+    strategy:
+      max-parallel: 20
+      matrix:
+        python-version: ["3.10", "3.12"]
+        pytorch-version: [2.5.1, 2.7.1, 2.8.0, 2.9.1]
+        use-conda: [false]
+    steps:
+      - uses: actions/checkout@master
+      - uses: actions/cache@v5
+        with:
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      # - uses: actions/cache@v5
+      #   with:
+      #     path: tools
+      #     key: ${{ runner.os }}-tools-${{ github.run_id }}-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      - name: Install System Dependencies
+        uses: ./.github/actions/install-system-dependencies
       - name: test python
-        run: |
-          source tools/activate_python.sh
-          ./ci/test_python_espnet2.sh
+        run: ./ci/test_python_espnet2.sh
       - uses: codecov/codecov-action@v5
         with:
           flags: test_python_espnet2
@@ -70,32 +98,29 @@ jobs:
 
   test_utils_espnet2:
     runs-on: ubuntu-latest
-    needs: process_labels
-    permissions:
-      contents: read
-      packages: read
+    needs: setup_environment
     if: |
       github.event.pull_request.draft == false
-    container:
-      image: ghcr.io/${{ github.repository_owner }}/espnet-ci:py${{ matrix.python-version }}-torch${{ matrix.pytorch-version }}
-      credentials:
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
     strategy:
       max-parallel: 20
       matrix:
         python-version: ["3.10", "3.12"]
         pytorch-version: [2.7.1]
+        use-conda: [false]
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@master
       - uses: actions/cache@v5
         with:
           path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}
+          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      # - uses: actions/cache@v5
+      #   with:
+      #     path: tools
+      #     key: ${{ runner.os }}-tools-${{ github.run_id }}-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      - name: Install System Dependencies
+        uses: ./.github/actions/install-system-dependencies
       - name: test utils
-        run: |
-          source tools/activate_python.sh
-          ./ci/test_utils.sh
+        run: ./ci/test_utils.sh
       - uses: codecov/codecov-action@v5
         with:
           flags: test_utils
@@ -107,64 +132,62 @@ jobs:
 
   test_shell_espnet2:
     runs-on: ubuntu-latest
-    needs: process_labels
-    permissions:
-      contents: read
-      packages: read
+    needs: setup_environment
     if: |
       github.event.pull_request.draft == false
-    container:
-      image: ghcr.io/${{ github.repository_owner }}/espnet-ci:py${{ matrix.python-version }}-torch${{ matrix.pytorch-version }}
-      credentials:
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
     strategy:
       max-parallel: 20
       matrix:
         python-version: ["3.10"]
         pytorch-version: [2.7.1]
+        use-conda: [false]
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@master
       - uses: actions/cache@v5
         with:
           path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}
+          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      # - uses: actions/cache@v5
+      #   with:
+      #     path: tools
+      #     key: ${{ runner.os }}-tools-${{ github.run_id }}-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      - name: Install System Dependencies
+        uses: ./.github/actions/install-system-dependencies
       - name: test shell
         run: |
-          source tools/activate_python.sh
           ./ci/test_shell_espnet2.sh
 
   test_integration_espnet2:
     runs-on: ubuntu-latest
-    needs: process_labels
-    permissions:
-      contents: read
-      packages: read
+    needs: setup_environment
     if: |
       github.event.pull_request.draft == false
-    container:
-      image: ghcr.io/${{ github.repository_owner }}/espnet-ci:py${{ matrix.python-version }}-torch${{ matrix.pytorch-version }}
-      credentials:
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
     strategy:
       max-parallel: 20
       matrix:
         python-version: ["3.10", "3.12"]
         pytorch-version: [2.5.1, 2.9.1]
+        use-conda: [false]
         config-task: ["asr", "tts", "asr2",  "enh", "ssl", "st", "spk", "lid", "s2t", "s2st", "lm", "codec"]
         exclude:
             - python-version: "3.12"
               pytorch-version: 2.5.1
+              use-conda: false
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@master
       - uses: actions/cache@v5
         with:
           path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}
+          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      # - uses: actions/cache@v5
+      #   with:
+      #     path: tools
+      #     key: ${{ runner.os }}-tools-${{ github.run_id }}-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      - name: Install System Dependencies
+        uses: ./.github/actions/install-system-dependencies
       - name: test espnet2 integration
         run: |
-          source tools/activate_python.sh
+          echo "Raising error for testing cache" && exit 1
           ./ci/test_integration_espnet2.sh ${{ matrix.config-task }}
       - uses: codecov/codecov-action@v5
         with:
@@ -172,64 +195,61 @@ jobs:
 
   test_configuration_espnet2:
     runs-on: ubuntu-latest
-    needs: process_labels
-    permissions:
-      contents: read
-      packages: read
+    needs: setup_environment
     if: |
       github.event.pull_request.draft == false
-    container:
-      image: ghcr.io/${{ github.repository_owner }}/espnet-ci:py${{ matrix.python-version }}-torch${{ matrix.pytorch-version }}
-      credentials:
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
     strategy:
       max-parallel: 20
       matrix:
         python-version: ["3.10"]
         pytorch-version: ["2.7.1"]
         config-task: ["asr", "asr_transducer", "lm", "ssl", "tts", "enh",  "enh_asr"]
+        use-conda: [false]
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@master
       - uses: actions/cache@v5
         with:
           path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}
+          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      # - uses: actions/cache@v5
+      #   with:
+      #     path: tools
+      #     key: ${{ runner.os }}-tools-${{ github.run_id }}-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      - name: Install System Dependencies
+        uses: ./.github/actions/install-system-dependencies
       - name: test configuration
-        run: |
-          source tools/activate_python.sh
-          ./ci/test_configuration_espnet2.sh ${{ matrix.config-task }}
+        run: ./ci/test_configuration_espnet2.sh ${{ matrix.config-task }}
       - uses: codecov/codecov-action@v5
         with:
           flags: test_configuration_espnet2
 
   test_python_espnet3:
     runs-on: ubuntu-latest
-    needs: process_labels
-    permissions:
-      contents: read
-      packages: read
+    needs: setup_environment
     if: |
       github.event.pull_request.draft == false
-    container:
-      image: ghcr.io/${{ github.repository_owner }}/espnet-ci:py${{ matrix.python-version }}-torch${{ matrix.pytorch-version }}
-      credentials:
-        username: ${{ github.actor }}
-        password: ${{ secrets.GITHUB_TOKEN }}
     strategy:
       max-parallel: 20
       matrix:
         python-version: ["3.10", "3.12"]
         pytorch-version: [2.5.1, 2.7.1, 2.8.0, 2.9.1]
+        chainer-version: [6.0.0]
+        use-conda: [false]
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@master
       - uses: actions/cache@v5
         with:
           path: ~/.cache/pip
-          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}
+          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      # - uses: actions/cache@v5
+      #   with:
+      #     path: tools
+      #     key: ${{ runner.os }}-tools-${{ github.run_id }}-${{ matrix.python-version }}-${{ matrix.pytorch-version }}-${{ hashFiles('**/pyproject.toml') }}-${{ hashFiles('**/Makefile') }}
+      - name: Install System Dependencies
+        uses: ./.github/actions/install-system-dependencies
       - name: test python
         run: |
-          source tools/activate_python.sh
+          echo "Raising error for testing cache" && exit 1
           ./ci/test_python_espnet3.sh
       - uses: codecov/codecov-action@v5
         with:
@@ -251,7 +271,7 @@ jobs:
         python-version: ["3.10"]
         pytorch-version: [2.7.1]
     steps:
-    - uses: actions/checkout@v4
+    - uses: actions/checkout@master
     - name: Set up Python
       uses: actions/setup-python@v6
       with:
@@ -294,5 +314,5 @@ jobs:
     if: |
       github.event.pull_request.draft == false
     steps:
-    - uses: actions/checkout@v4
+    - uses: actions/checkout@master
     - run: ci/check_kaldi_symlinks.sh
